- hosts: routers
  gather_facts: no
  vars_prompt:
    - name: IOS_User_Prompt
      prompt: "Enter Cisco IOS Username"
      private: no 
    - name: IOS_Password_Prompt
      prompt: "Enter IOS Password"
      private: yes

  tasks:
    - set_fact:   
        ios_user: "{{ IOS_User_Prompt }}"     
        ios_password: "{{ IOS_Password_Prompt }}"
      no_log: true
      delegate_to: localhost
      run_once: true

    - name: Retrieve and save IP route table
      ios_command:
        commands:
          - show ip route
      register: route_output

    - name: unique out for each router
      copy:
        content: "{{ route_output.stdout[0] }}"
        dest: "/home/aws_user/Documents/AWX/AWX_router_info/AWX_router_info_{{ inventory_hostname }}_ip_route.txt"
      delegate_to: localhost

