---
- name: Configure nginx
  hosts: awx

    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: present
      become: true

    - name: Ensure NGINX is running and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
      become: true

